# ****
# Massage tags used in the sending and receiving of data
# ****

SUFFIX_TAG = '[SUFFIX_CALCULATOR]'

HANG_MAN_TAG = '[HANG_MAN]'
HANG_MAN_CREATION_TAG = '[HANG_MAN_CREATION]'
HANG_MAN_START_DETAILS_TAG = '[HANG_MAN_START_DETAILS_CREATION]'
GAME_WIN_MSG = '[GAME_WIN]'
GAME_LOSE_MSG = '[GAME_LOSE]'

CHAT_ROOM_TAG = '[CHAT_ROOM]'
CREATE_CHAT_ROOM = '[CREATE_CHAT_ROOM]'
EXIT_CHAT_ROOM_TAG = '[EXIT_CHAT_ROOM]'
JOIN_CHAT_ROOM_TAG = '[JOIN_CHAT_ROOM]'
GET_CONNECTED_USERS_TAG = '[GET_CONNECTED_USERS]'

USER_NAME_TAG = '[USER_NAME]'

DISCONNECT_MSG = "!DISCONNECT"  # For clean disconnection of client
EXIT_UTILITY_MSG = "!EXIT"  # Exit out of current utility

INPUT_ERROR_MSG = '[INPUT_ERROR]'
DISCONNECT_RESULT_MSG = "[DISCONNECT]"


